disabled_rules:
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
  - identifier_name
  - empty_first_line

opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

included:
  - CleanMate
excluded:
  - Pods
  - CleanMate/Resources
  - "**/*.generated.swift"

line_length:
  warning: 120
  error: 150

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 700

type_name:
  min_length: 3
  max_length: 40

function_parameter_count:
  warning: 6
  error: 8

cyclomatic_complexity:
  warning: 10
  error: 15

reporter: "xcode"

custom_rules:
  array_constructor:
    name: "Array/Dictionary Constructor"
    regex: '[let,var] .+ = (\[.+\]\(\))'
    capture_group: 1
    message: "Prefer array/dictionary literal syntax over constructor."
    severity: warning

  comments_space:
    name: "Space After Comment"
    regex: '//\S'
    message: "There should be a space after //"
    severity: warning
