excluded:
  - Pods
  - CleanMate/CleanMateTests
  - CleanMate/CleanMateUITests

disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - sorted_imports
  - object_literal
  - number_separator
  - prohibited_super_call
  - fatal_error_message

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id
    - URL
    - x
    - y

type_name:
  min_length:
    warning: 3
  excluded:
    - URL
    - ID

line_length:
  warning: 120
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

file_length:
  warning: 400
  error: 1000

cyclomatic_complexity:
  warning: 15
  error: 25

reporter: "xcode"
