name: Deploy to TestFlight

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to TestFlight
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
          bundler-cache: true

      - name: Install Cocoapods
        env:
          LANG: en_US.UTF-8
        run: |
          cd CleanMate
          gem install cocoapods
          pod repo update
          pod install --verbose

      - name: Set up certificates
        env:
          CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_BASE64 }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
          KEYCHAIN_PASSWORD: cleanmate123
          KEYCHAIN_PATH: ${{ runner.temp }}/app-signing.keychain-db
        run: |
          # Clean up any existing keychain
          security delete-keychain $KEYCHAIN_PATH || true
          
          # Create a new keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH || exit 1
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH || exit 1
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH || exit 1
          
          # Import certificate to keychain
          echo -n "$CERTIFICATE_BASE64" | base64 --decode > /tmp/certificate.p12 || exit 1
          security import /tmp/certificate.p12 -k $KEYCHAIN_PATH -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign || exit 1
          
          # Add keychain to search list
          security list-keychains -d user -s $KEYCHAIN_PATH $(security list-keychains -d user | tr -d '"') || exit 1
          security default-keychain -s $KEYCHAIN_PATH || exit 1
          
          # Allow codesign to access keychain
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH || exit 1
          
          # Verify setup
          security find-identity -v -p codesigning $KEYCHAIN_PATH || exit 1

      - name: Prepare Build Directory
        run: |
          mkdir -p CleanMate/build

      - name: Build and Deploy
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: |
          cd CleanMate
          
          # Build the app
          xcodebuild -workspace CleanMate.xcworkspace -scheme CleanMate -configuration Release -archivePath build/CleanMate.xcarchive clean archive CODE_SIGN_STYLE=Manual DEVELOPMENT_TEAM=$APPLE_TEAM_ID || exit 1
          
          # Export the app
          xcodebuild -exportArchive -archivePath build/CleanMate.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build || exit 1
          
          # Upload to TestFlight
          xcrun altool --upload-app --type ios --file build/CleanMate.ipa --username "$APPLE_ID" --password "$APPLE_APP_SPECIFIC_PASSWORD" || exit 1

      - name: Cleanup Keychain
        if: always()
        run: |
          security delete-keychain $KEYCHAIN_PATH || true
