name: Deploy to TestFlight

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to TestFlight
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
          bundler-cache: true

      - name: Debug Project Structure
        run: |
          echo "Root directory:"
          pwd
          echo "\nRoot contents:"
          ls -la
          echo "\nCleanMate directory contents:"
          ls -la CleanMate
          echo "\nVerifying Xcode project:"
          test -d "CleanMate/CleanMate.xcodeproj" && echo "✅ Xcode project found" || echo "❌ Xcode project not found"

      - name: Install Cocoapods
        env:
          LANG: en_US.UTF-8
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          gem install cocoapods
          pod repo update
          pod install --verbose

      - name: Set up certificates
        env:
          CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_BASE64 }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
        run: |
          # Delete keychain if it exists
          security delete-keychain build.keychain || true
          
          # Create keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security set-keychain-settings -t 3600 -l ~/Library/Keychains/build.keychain

          # Import certificate
          echo $CERTIFICATE_BASE64 | base64 --decode > certificate.p12
          security import certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain

      - name: Deploy to TestFlight
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          MATCH_KEYCHAIN_NAME: build.keychain
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
        run: bundle exec fastlane beta

      - name: Cleanup Keychain
        if: always()
        run: |
          security delete-keychain build.keychain || true
