name: Deploy to TestFlight

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '**/*.swift'
      - '**/*.xcodeproj/**'
      - '**/*.xcworkspace/**'
      - 'Podfile'
      - 'Podfile.lock'
      - '.github/workflows/deploy.yml'

permissions: write-all

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'

      - name: Install CocoaPods
        run: |
          gem install cocoapods
          gem install xcpretty

      - name: Install Dependencies
        run: |
          pod install
        
      - name: Cache Pods
        uses: actions/cache@v3
        with:
          path: Pods
          key: macOS-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            macOS-pods-

      - name: Verify Secrets
        env:
          CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_BASE64 }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          PROVISIONING_PROFILE_BASE64: ${{ secrets.PROVISIONING_PROFILE_BASE64 }}
        run: |
          echo "Checking secrets format..."
          
          # Check CERTIFICATE_BASE64
          if [ -z "$CERTIFICATE_BASE64" ]; then
            echo " CERTIFICATE_BASE64 is empty"
            exit 1
          else
            echo " CERTIFICATE_BASE64 is set (length: ${#CERTIFICATE_BASE64})"
          fi
          
          # Check CERTIFICATE_PASSWORD
          if [ -z "$CERTIFICATE_PASSWORD" ]; then
            echo " CERTIFICATE_PASSWORD is empty"
            exit 1
          else
            echo " CERTIFICATE_PASSWORD is set (length: ${#CERTIFICATE_PASSWORD})"
            # Check for common issues
            if [[ "$CERTIFICATE_PASSWORD" =~ ^[[:space:]] || "$CERTIFICATE_PASSWORD" =~ [[:space:]]$ ]]; then
              echo " CERTIFICATE_PASSWORD contains leading/trailing whitespace"
              exit 1
            fi
          fi
          
          # Check APPLE_TEAM_ID
          if [ -z "$APPLE_TEAM_ID" ]; then
            echo " APPLE_TEAM_ID is empty"
            exit 1
          else
            echo " APPLE_TEAM_ID is set (length: ${#APPLE_TEAM_ID})"
          fi
          
          # Check APPLE_ID
          if [ -z "$APPLE_ID" ]; then
            echo " APPLE_ID is empty"
            exit 1
          else
            echo " APPLE_ID is set (length: ${#APPLE_ID})"
          fi
          
          # Check APPLE_APP_SPECIFIC_PASSWORD
          if [ -z "$APPLE_APP_SPECIFIC_PASSWORD" ]; then
            echo " APPLE_APP_SPECIFIC_PASSWORD is empty"
            exit 1
          else
            echo " APPLE_APP_SPECIFIC_PASSWORD is set (length: ${#APPLE_APP_SPECIFIC_PASSWORD})"
          fi

          # Check PROVISIONING_PROFILE_BASE64
          if [ -z "$PROVISIONING_PROFILE_BASE64" ]; then
            echo " PROVISIONING_PROFILE_BASE64 is empty"
            exit 1
          else
            echo " PROVISIONING_PROFILE_BASE64 is set"
          fi
          
          echo "Verifying certificate decoding..."
          if ! echo "$CERTIFICATE_BASE64" | base64 -d > /tmp/test_cert.p12 2>/dev/null; then
            echo " CERTIFICATE_BASE64 is not valid base64"
            exit 1
          else
            echo " CERTIFICATE_BASE64 is valid base64"
            ls -l /tmp/test_cert.p12
            file /tmp/test_cert.p12
            rm /tmp/test_cert.p12
          fi

      - name: Import Certificate
        env:
          CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_BASE64 }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
          PROVISIONING_PROFILE_BASE64: ${{ secrets.PROVISIONING_PROFILE_BASE64 }}
          KEYCHAIN_PATH: /Users/runner/Library/Keychains/build.keychain-db
        run: |
          # Echo steps for debugging
          echo "Setting up keychain..."
          
          # Set keychain password
          KEYCHAIN_PASSWORD="temporary"
          
          # Create temporary certificate file
          echo "Creating temporary certificate..."
          echo "$CERTIFICATE_BASE64" | base64 --decode > certificate.p12
          
          # Create provisioning profile
          echo "Creating provisioning profile..."
          echo "$PROVISIONING_PROFILE_BASE64" | base64 --decode > profile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
          
          # Print certificate file info
          echo "Certificate file info:"
          ls -l certificate.p12
          file certificate.p12
          
          # Create keychain
          echo "Creating keychain..."
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          
          # Configure keychain
          echo "Configuring keychain..."
          security set-keychain-settings -t 3600 -l "$KEYCHAIN_PATH"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          
          # Add to keychain list
          echo "Adding to keychain list..."
          security list-keychains -d user -s "$KEYCHAIN_PATH" $(security list-keychains -d user | tr -d '"')
          
          # Import certificate
          echo "Importing certificate..."
          security import certificate.p12 -k "$KEYCHAIN_PATH" -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign -A
          
          # Update keychain search list
          echo "Updating keychain search list..."
          security list-keychains -s "$KEYCHAIN_PATH"
          
          # Set as default keychain
          echo "Setting as default keychain..."
          security default-keychain -s "$KEYCHAIN_PATH"
          
          # Set partition list
          echo "Setting partition list..."
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          
          # Verify setup
          echo "Verifying setup..."
          security find-identity -v -p codesigning "$KEYCHAIN_PATH"
          
          # Clean up certificate file
          echo "Cleaning up..."
          rm certificate.p12
          rm profile.mobileprovision

      - name: Build and Deploy
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
        run: |
          # Create build directory
          BUILD_DIR="${GITHUB_WORKSPACE}/build"
          mkdir -p "$BUILD_DIR"
          
          # Build the app
          echo "Building app..."
          xcodebuild -workspace CleanMate.xcworkspace \
            -scheme CleanMate \
            -configuration Release \
            -archivePath "$BUILD_DIR/CleanMate.xcarchive" \
            -destination 'generic/platform=iOS' \
            clean archive \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=$APPLE_TEAM_ID \
            PROVISIONING_PROFILE_SPECIFIER="CleanMate Development Profile" \
            CODE_SIGN_IDENTITY="Apple Development" \
            | xcpretty
          
          # Export the app
          echo "Exporting app..."
          xcodebuild -exportArchive \
            -archivePath "$BUILD_DIR/CleanMate.xcarchive" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "$BUILD_DIR" \
            | xcpretty
          
          # Upload to TestFlight
          echo "Uploading to TestFlight..."
          xcrun altool --upload-app \
            --type ios \
            --file "$BUILD_DIR/CleanMate.ipa" \
            --username "$APPLE_ID" \
            --password "$APPLE_APP_SPECIFIC_PASSWORD" \
            --team-id "$APPLE_TEAM_ID"

      - name: Cleanup
        if: always()
        run: |
          security delete-keychain /Users/runner/Library/Keychains/build.keychain-db || true
