name: Deploy to TestFlight

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions: write-all

jobs:
  debug:
    name: Debug Environment
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug Info
        run: |
          echo "Current working directory:"
          pwd
          echo "\nDirectory contents:"
          ls -la
          echo "\nGit status:"
          git status
          echo "\nGit remote:"
          git remote -v