name: Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  swiftlint:
    name: SwiftLint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run SwiftLint
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict

  podlint:
    name: Pod Lint
    runs-on: macos-15
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.0'
        bundler-cache: true
    
    - name: Pod Lint
      run: |
        gem install cocoapods
        pod lib lint --allow-warnings --no-clean --verbose
